version: '3.8'

services:
  flask_app:
    build: ./microservices/back-end
    container_name: flask_app
    command: python serveur.py
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - mongodb
      - rabbitmq
    networks:
      - app_network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: badr
      POSTGRES_DB: users
    networks:
      - app_network

  redis:
    image: redis
    restart: always
    networks:
      - app_network

  mongodb:
    image: mongo
    restart: always
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
